version: '3.8'

services:
  server:
    image: money-tracker-backend-api
    container_name: "money-tracker-backend-api"
    build: ./
    command: ./wait-for-postgres.sh db ./app
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432