version: '3.8'

services:
  server:
    image: money-tracker-backend-api
    container_name: "money-tracker-backend-api"
    build: ./
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    ports:
      - 8080:8080
    environment:
      - DB_PASSWORD
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432