basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: API server for money-tracker application.
  title: Money-tracker API
  version: v1
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
